spring:
  application:
    name: beershop-api-gateway

zuul:
  ignoredServices: '*'
  routes:
    beershop:
      path: /beershop/**
      url: http://localhost:8090

beershop:
  ui:
    baseUrl: http://localhost:4200